dist: bionic
language: go
go:
  - 1.x
env:
  global:
    - LANG=C
    - LC_ALL=C
deploy:
  provider: releases
  api_key:
    secure: vBUokTv94n8s65STUgTiD6I0Iy8KXbBRvQUrAof8XG+U4ZMsH5PmDTpS+wz+SaxI6o0PRkfyOiPVdARhiKAFnfatG3q9EHllMQwqRR2YIju51A3aCxgEJ5uWDoybwQdipERUMMYwUO/8XZaRRpwFD2bdQBFWkBtQyMcAkrEL8BXckwQQ531oDN2hK5gAiTllqsOswV2idwUlBRU9jOtStzff+UgUYsp/ZebsRodyOYkEB2Ev15yARo2HTXbyZ2icwHPtMbx5zmNUSRtxs9a4hfzaK3m6ctK8qLYYUdQvXub/ruuACapdw4Ez88LY1agTecbZhFYmJzv8oANH1e4VUI4owuHnZCpU6LRutS4wOhglrkOrGo6lSUlJeA+RtQjyjBugjej9DDtDyyIlRU1ZaBF3qWR9N5EXKuquf0olOfmUR67ap1NykE9VUpzkYjkoVRTiPs/e2onM/nRNOvAQcIt75FD13u+Y/DcYQ8r7KpMIu1HNdtbVx8gMeq76bRhP1YdDg2jm+DdJ21KWjf5QHsbyoXDfJzdKlCloLIlAU3EPJhMoXsnNzre0/FXeUl6dfteR1axNS6U7e/vKsQ9rlUFZWIQaeVPjfXmFKblNNVQ5uFrrsB/EGHcJl7IUx5fvcRT5hMMNwC660YxVkBXDbRb5fxMW5/+K0BOi9cP6en8=
  skip_cleanup: true
  file_glob: true
  file: pwnagotchi-*.zip
  on:
    tags: true
    repo: evilsocket/pwnagotchi
branches:
  only:
    - "/^v[0-9]+\\.[0-9]+\\.[0-9]+[A-Za-z0-9]+?$/"
cache:
  apt: true
before_script:
  - wget https://download.qemu.org/qemu-4.1.0.tar.xz
  - tar xvJf qemu-4.1.0.tar.xz
  - cd qemu-4.1.0
  - "./configure --target-list=arm-softmmu"
  - make -j$(nproc)
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - sudo apt-get -y update || true
  - sudo apt-get -y install qemu-user-static binfmt-support bmap-tools kpartx
  - sudo update-binfmts --display
script:
  - sudo make clean
  - sudo -E env "PATH=$PATH" make install
  - sudo make image -e PWN_HOSTNAME=pwnagotchi VERSION=$TRAVIS_TAG
notifications:
  slack:
    rooms:
      - secure: "aovN87lswg+TTLobxJpevC0p2F4omTAlsOzeKqLysRW55o5rRhRC1SgwRkWUl19yr49nsyffwmv/b7OcyQiWIVnz1bxxE9XOKP8zgRMA/bKKcyAcPktPqHXsALIQDseXyl0kz7fwdkRWg0UC2HpKqi5koAhmBYTX/fbzieyeHCbcQ7lbFfVFIepE1401y9m1IqUHcHuGfFhMvTaSDIpXrDXnWdA8+gDAl0HKJv41MIsgmffbh/QhD2jLBWzItjxFC3llmNfy88pnzCk0+HBMY/4272LXb0czX7et5HJeM74oxPqkb3aKXFxZgNaDl7cYdV+kzj9dfKUk47hAqwbxlirit5WvHI1Br1VyA90+PFvcC/p41J8gCv0IlcB5vjWN8NKWA1J+Y1F+KvrujMvGtgd0foHZvaSutuRODhI1cBh5rYAiLCroRSlvKMw3IJRyCRstYgUlMIJ3cI2Ova/kU44KtDVmjT9VE/pPkhkHBPvcYThL6skZTdl19E/RlormLu3XObG1aHLZ+Znxe/aL7tWHi0KMOlpy+TMDdps4go7URnJ8yitHtIvU/zMtBrztIwN0Oy2JLKXrS5qIijmRAkBLxe0NxuG01DYFzEO3KtnRirP4uSe3QcrjyP4sqPrVhrjl3TR6gwg8V1juvDXB4e2h8yCpaUW5AdSBOlx9riY="# here when i got here
      - secure: "KZJx5I32Vme1L3UmWYTMs5WgAE795XMcgOgzHiZAX0y2tQol4ldEczonXg6h74HxZTXcdgdCWFNLwdSmnPKMIWNZq8nZZmbCZ2mU2PjsqZwheEv8dzfNAVubhH+5udhaAsfyyBkR+dSn5SpmxDO2pV91HAt/SZjejqxqjy8sodi05iZD+6cYR8fuiK4JfrV91ptIqwschfhmzmLF1YeyTsD80GOHQiOeLv7kPbdvBmj2QEjKg48RZyAdEYOFJAIO4EUET+lLw/eYHUpOsfe4tQqfmcyWKGZCHqZL3BP+IKNrskCSV2s/624zeCkaPEPffY+yxFA3i60CkNnHMhE3oW/S8lPkP76Nj11lfUov9oxn2qxft1ze3HiQN9ifqKlRkPt3T+AyMwhqyd6m9tIlBlT2Wq7K6IzY1XwCqrQuYPPF0/QyK6m5jG+xlEuzVzSSvhxo7QFgwT493BPyO+YpuRnYqyCOMDFPeB+L/SIArCtZ4KsD1g221KxQx9qK5Ik0mf2M07oS1uMRIcK6PhkuunbGize8aYuSnfBF+rnG/VlmwCie2p7JLLkFdYxAKdnznZPudKvvhK19xZaINXhcbHCq6K2m3wAy+8eiacRVzkHI2c4kFZw9neyAiF1Nob6TUBm0MaH+eaf1DCXUFwkZrG0BgcLtxnNn4mOE+su29jU="# this is for the travis_build channel
    on_success: always
    on_failure: always
    on_pull_requests: false
    
