name: CI

on: [push, pull_request]

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install qemu
        run: sudo apt-get -y update && sudo apt-get -y install qemu-system-arm qemu-user-static binfmt-support bmap-tools kpartx && sudo update-binfmts --display
      - name: create image
        run: make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=0.0.1
